services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "bkR4c-8yiRxK93nfuuYyvcZcwh69977t"
      MYSQL_DATABASE: revive
      MYSQL_USER: revive
      MYSQL_PASSWORD: "bkR4c-8yiRxK93nfuuYyvcZcwh69977t"
    volumes:
      - revive_db:/var/lib/mysql

  revive:
    image: ghcr.io/sternbaureihe/revive-adserver:latest
    restart: always
    depends_on: [db]
    ports:
      - "127.0.0.1:8086:80"
    environment:
      DB_HOST: db
      DB_USER: revive
      DB_PASSWORD: "bkR4c-8yiRxK93nfuuYyvcZcwh69977t"
      DB_NAME: revive
    volumes:
      - revive_data:/var/www/html/var

volumes:
  revive_db:
  revive_data:
